//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceTennisDenisDll {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiceTennisDenisDll.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The configuration has not been initialized..
        /// </summary>
        internal static string ConfigurationNotInitializedException {
            get {
                return ResourceManager.GetString("ConfigurationNotInitializedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following exception has occured while testing the connection string :.
        /// </summary>
        internal static string InvalidConnectionStringException {
            get {
                return ResourceManager.GetString("InvalidConnectionStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The columns count doesn&apos;t match the headers count..
        /// </summary>
        internal static string InvalidDatasToHeadersException {
            get {
                return ResourceManager.GetString("InvalidDatasToHeadersException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid content for the specified matches file..
        /// </summary>
        internal static string InvalidMatchesFileDatasException {
            get {
                return ResourceManager.GetString("InvalidMatchesFileDatasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid content for the players file..
        /// </summary>
        internal static string InvalidPlayersFileDatasException {
            get {
                return ResourceManager.GetString("InvalidPlayersFileDatasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The  instance has not been initialized..
        /// </summary>
        internal static string NotInitializedInstanceException {
            get {
                return ResourceManager.GetString("NotInitializedInstanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file found for the specified year in the data directory configured..
        /// </summary>
        internal static string NoYearDataFileFoundException {
            get {
                return ResourceManager.GetString("NoYearDataFileFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Players datas file not found..
        /// </summary>
        internal static string PlayersDatasFileNotFoundException {
            get {
                return ResourceManager.GetString("PlayersDatasFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified ranking ruleset doesn&apos;t existe..
        /// </summary>
        internal static string RankingRulesetNotFoundException {
            get {
                return ResourceManager.GetString("RankingRulesetNotFoundException", resourceCulture);
            }
        }
    }
}
