//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceTennisDenisCore.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiceTennisDenisCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SET SQL_MODE = &quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        ///SET time_zone = &quot;+00:00&quot;;
        ///
        ///CREATE TABLE `configuration` (
        ///  `id` int(10) UNSIGNED NOT NULL,
        ///  `best_performances_count_for_ranking` int(10) UNSIGNED NOT NULL,
        ///  `ranking_weeks_count` int(10) UNSIGNED NOT NULL
        ///) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
        ///
        ///CREATE TABLE `edition` (
        ///  `id` int(10) UNSIGNED NOT NULL,
        ///  `year` int(10) UNSIGNED NOT NULL,
        ///  `code` varchar(255) COLLATE utf8_bin NOT NULL,
        ///  `name` varchar(255) COLLATE utf8_bin NOT NULL,
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string nice_tennis_denis {
            get {
                return ResourceManager.GetString("nice_tennis_denis", resourceCulture);
            }
        }
    }
}
